# Generated by Django 5.0.7 on 2024-08-10 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0002_revisoesmodel_proxima_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 22, 13, 54, 322517)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 8, 9, 22, 13, 54, 322517)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='url_notion',
            field=models.URLField(max_length=500),
        ),
    ]
