# Generated by Django 5.0.7 on 2024-10-12 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0006_alter_pequenasrevisoesmodel_proxima_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pequenasrevisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 15, 4, 14, 63074)),
        ),
        migrations.AlterField(
            model_name='pequenasrevisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 15, 4, 14, 63074)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 15, 4, 14, 63074)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 10, 12, 15, 4, 14, 63074)),
        ),
    ]
