# Generated by Django 5.0.7 on 2024-12-01 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0007_alter_pequenasrevisoesmodel_proxima_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PequenasRevisoesModel',
        ),
        migrations.AddField(
            model_name='revisoesmodel',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 1, 18, 2, 5, 348445)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 1, 18, 2, 5, 348445)),
        ),
    ]
