# Generated by Django 5.0.7 on 2024-12-16 01:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0008_delete_pequenasrevisoesmodel_revisoesmodel_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 9, 54, 979992)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 9, 54, 978992)),
        ),
    ]
