# Generated by Django 5.0.7 on 2024-12-16 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0013_alter_revisoesmodel_proxima_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 19, 44, 157325)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 19, 44, 157325)),
        ),
    ]
