# Generated by Django 5.0.7 on 2024-12-16 01:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assunto_revisao', '0001_initial'),
        ('revisoes', '0014_alter_revisoesmodel_proxima_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisoesmodel',
            name='assunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assunto_revisao.assuntorevisaomodel'),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 22, 30, 565031)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 22, 30, 565031)),
        ),
    ]
