# Generated by Django 5.0.7 on 2024-12-16 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0015_revisoesmodel_assunto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisoesmodel',
            old_name='assunto',
            new_name='assunto_id',
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 23, 32, 940192)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 23, 32, 940192)),
        ),
    ]
