# Generated by Django 5.0.7 on 2024-12-16 01:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0016_rename_assunto_revisoesmodel_assunto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisoesmodel',
            old_name='assunto_id',
            new_name='assunto',
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 24, 5, 134453)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 24, 5, 134453)),
        ),
    ]
