# Generated by Django 5.0.7 on 2024-12-16 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0017_rename_assunto_id_revisoesmodel_assunto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisoesmodel',
            name='numero_revisao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 25, 4, 811255)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 25, 4, 811255)),
        ),
    ]
