# Generated by Django 5.0.7 on 2024-12-16 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0018_revisoesmodel_numero_revisao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisoesmodel',
            name='numero_revisao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 35, 14, 480023)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 12, 15, 22, 35, 14, 480023)),
        ),
    ]
