# Generated by Django 5.0.7 on 2024-08-05 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevisoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('url_notion', models.URLField(max_length=100)),
                ('ultima_data', models.DateField(default=datetime.datetime(2024, 8, 4, 21, 16, 6, 903717))),
                ('intervalo_revisao', models.IntegerField()),
                ('dificuldade', models.CharField(choices=[('f', 'fácil'), ('m', 'médio'), ('d', 'difícil')], default='m', max_length=1)),
            ],
        ),
    ]
