# Generated by Django 5.0.7 on 2024-08-05 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 21, 19, 48, 844493)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 21, 19, 48, 844493)),
        ),
    ]
