# Generated by Django 5.0.7 on 2024-09-01 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0003_alter_revisoesmodel_proxima_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PequenasRevisoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('url_notion', models.URLField(max_length=500)),
                ('ultima_data', models.DateField(default=datetime.datetime(2024, 9, 1, 20, 48, 9, 612375))),
                ('proxima_data', models.DateField(default=datetime.datetime(2024, 9, 1, 20, 48, 9, 612375))),
                ('intervalo_revisao', models.IntegerField()),
                ('dificuldade', models.CharField(choices=[('f', 'fácil'), ('m', 'médio'), ('d', 'difícil')], default='m', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 9, 1, 20, 48, 9, 611374)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 9, 1, 20, 48, 9, 611374)),
        ),
    ]
