# Generated by Django 5.0.7 on 2024-09-01 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revisoes', '0004_pequenasrevisoesmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pequenasrevisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 9, 1, 20, 54, 49, 959783)),
        ),
        migrations.AlterField(
            model_name='pequenasrevisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 9, 1, 20, 54, 49, 959783)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='proxima_data',
            field=models.DateField(default=datetime.datetime(2024, 9, 1, 20, 54, 49, 959783)),
        ),
        migrations.AlterField(
            model_name='revisoesmodel',
            name='ultima_data',
            field=models.DateField(default=datetime.datetime(2024, 9, 1, 20, 54, 49, 959783)),
        ),
    ]
